name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: your-vps-ip
          username: your-vps-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu /var/www/html
            sudo chmod -R 755 /var/www/html
            git config --global --add safe.directory /var/www/html
            cd /var/www/html
            git pull origin main
